stages:
  - info
  - print

job_info_1:
  stage: info
  tags:
    - quickbite
  script:
    - echo "Bắt đầu thu thập thông tin hệ thống..."
    - uname -a

job_info_2:
  stage: info
  tags:
    - quickbite
  script:
    - echo "Bắt đầu kiểm tra môi trường..."
    - whoami

job_print:
  stage: print
  tags:
    - quickbite
  script:
    - echo "In ra kết quả cuối cùng từ pipeline..."