image: docker:latest


stages:
  - test_image


test_docker_image_job:
  stage: test_image
  tags:
    - quickbite
  script:
    # 1. Đăng nhập tự động vào Registry sử dụng tài khoản tạm thời của job
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


    # 2. Kéo trực tiếp image phiên bản 1.0.0 đã được push từ local về Runner
    - docker pull $CI_REGISTRY_IMAGE:1.0.0


    # 3. Khởi chạy thử container từ image vừa kéo về để verify ứng dụng hoạt động ổn định
    - docker run -d --name verify_user_service -p 8081:8081 $CI_REGISTRY_IMAGE:1.0.0


    # 4. Chờ 5 giây để Spring Boot hoàn tất quá trình khởi động
    - sleep 5


    # 5. Kiểm tra danh sách container để xác nhận ứng dụng đang chạy ở trạng thái UP (exit code = 0)
    - docker ps


    # 6. Dọn dẹp môi trường (dừng và xóa container verify) trực tiếp trong script chính
    - docker rm -f verify_user_service
