spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quickbite_user_db}
    username: ${DB_USERNAME:quickbite_user}
    password: ${DB_PASSWORD:quickbite_user}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
jwt:
  secret:
    key: ${JWT_SECRET_KEY:daylachuoimahoabimatrikkei0987654321dacbietracroi}
  expired:
    access: ${JWT_EXPIRED_ACCESS:864000}
    refresh: ${JWT_EXPIRED_REFRESH:7}

server:
  port: ${SERVER_PORT:8081}