name: Tự động hoá đóng gói Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "user-service"

jobs:
  # Job biên dịch code ra file JAR
  build_jar:
    runs-on: [self-hosted, quickbite]
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v5

      - name: Thiết lập môi trường JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cấp quyền thực thi Gradle
        run: chmod +x ./gradlew

      - name: Biên dịch mã nguồn
        run: ./gradlew bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
          retention-days: 1

  # Job build Docker image sử dụng file JAR artifacts từ job trước
  build_image:
    needs: build_jar
    runs-on: [self-hosted, quickbite]
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v5

      - name: Tải file JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs/

      - name: Đóng gói Docker Image
        # Biên dịch Docker image từ Dockerfile đơn tầng trực tiếp trên daemon của máy host
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .