name: Parallel and Sequential Workflow

on:  
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v5
      - name: Cấp quyền thực thi cho gradlew
        run: chmod +x gradlew
      - name: Test và build artifacts
        run: ./gradlew bootJar